# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import record_metadata_options_pb2 as record__metadata__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x64\x64ress_book.proto\x12\x07\x65xample\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1drecord_metadata_options.proto\"0\n\x06Person\x12\x11\n\x02id\x18\x01 \x01(\x05\x42\x05\x8aM\x02\x08\x01\x12\x13\n\x04name\x18\x02 \x01(\tB\x05\x8aM\x02\x12\x00\"e\n\x07Message\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.example.MessageType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"]\n\x08\x43hatRoom\x12\x11\n\x02id\x18\x01 \x01(\x05\x42\x05\x8aM\x02\x08\x01\x12\x1f\n\x06people\x18\x02 \x03(\x0b\x32\x0f.example.Person\x12\x1d\n\x03msg\x18\x03 \x03(\x0b\x32\x10.example.Message*?\n\x0bMessageType\x12\x0c\n\x08USER_MSG\x10\x00\x12\x10\n\x0cSYS_JOIN_MSG\x10\x01\x12\x10\n\x0cSYS_LEFT_MSG\x10\x02\x62\x06proto3')

_MESSAGETYPE = DESCRIPTOR.enum_types_by_name['MessageType']
MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
USER_MSG = 0
SYS_JOIN_MSG = 1
SYS_LEFT_MSG = 2


_PERSON = DESCRIPTOR.message_types_by_name['Person']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_CHATROOM = DESCRIPTOR.message_types_by_name['ChatRoom']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'address_book_pb2'
  # @@protoc_insertion_point(class_scope:example.Person)
  })
_sym_db.RegisterMessage(Person)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'address_book_pb2'
  # @@protoc_insertion_point(class_scope:example.Message)
  })
_sym_db.RegisterMessage(Message)

ChatRoom = _reflection.GeneratedProtocolMessageType('ChatRoom', (_message.Message,), {
  'DESCRIPTOR' : _CHATROOM,
  '__module__' : 'address_book_pb2'
  # @@protoc_insertion_point(class_scope:example.ChatRoom)
  })
_sym_db.RegisterMessage(ChatRoom)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON.fields_by_name['id']._options = None
  _PERSON.fields_by_name['id']._serialized_options = b'\212M\002\010\001'
  _PERSON.fields_by_name['name']._options = None
  _PERSON.fields_by_name['name']._serialized_options = b'\212M\002\022\000'
  _CHATROOM.fields_by_name['id']._options = None
  _CHATROOM.fields_by_name['id']._serialized_options = b'\212M\002\010\001'
  _MESSAGETYPE._serialized_start=343
  _MESSAGETYPE._serialized_end=406
  _PERSON._serialized_start=95
  _PERSON._serialized_end=143
  _MESSAGE._serialized_start=145
  _MESSAGE._serialized_end=246
  _CHATROOM._serialized_start=248
  _CHATROOM._serialized_end=341
# @@protoc_insertion_point(module_scope)
